dist: trusty
sudo: required

language: node_js
node_js:
  - "node"

before_script:
 - npm install electron-builder -g
 
matrix:
  include:
    - os: osx
    - os: linux
      before_install:
        - sudo apt-get install --no-install-recommends -y gcc-multilib g++-multilib
        - wget -nc https://dl.winehq.org/wine-builds/Release.key
        - sudo apt-key add Release.key
        - sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
        - sudo apt-get install -y --install-recommends winehq-stable
cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run pack:all

branches:
  only:
    - master
